package cloud.catfish.mbg.plugin;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.TopLevelClass;

import java.util.List;

/**
 * Unified MyBatis Generator plugin for comprehensive domain model generation control.
 * 
 * <p>This plugin combines the functionality of three separate plugins:</p>
 * <ul>
 *   <li><strong>Date/Time Serialization:</strong> Adds @JsonFormat annotations for JSON serialization</li>
 *   <li><strong>Date/Time Deserialization:</strong> Adds @DateTimeFormat annotations for Spring MVC binding</li>
 *   <li><strong>Getter/Setter Control:</strong> Optionally disables getter/setter method generation</li>
 * </ul>
 * 
 * <p><strong>Features:</strong></p>
 * <ul>
 *   <li>Configurable JSON serialization format for date/time fields</li>
 *   <li>Configurable Spring MVC date/time binding format</li>
 *   <li>Optional getter/setter method generation control</li>
 *   <li>Flexible date/time pattern and timezone configuration</li>
 *   <li>Support for DATE, TIME, and TIMESTAMP database types</li>
 * </ul>
 * 
 * <p><strong>Configuration Properties:</strong></p>
 * <ul>
 *   <li><code>enableJsonFormat</code> - Enable @JsonFormat annotations (default: true)</li>
 *   <li><code>enableDateTimeFormat</code> - Enable @DateTimeFormat annotations (default: true)</li>
 *   <li><code>generateGetters</code> - Generate getter methods (default: true)</li>
 *   <li><code>generateSetters</code> - Generate setter methods (default: true)</li>
 *   <li><code>dateTimePattern</code> - Date/time pattern (default: "yyyy-MM-dd HH:mm:ss")</li>
 *   <li><code>timezone</code> - Timezone for JSON format (default: "GMT+8")</li>
 * </ul>
 * 
 * <p><strong>Usage Example:</strong></p>
 * <pre>
 * &lt;plugin type="cloud.catfish.mbg.plugin.DomainModelPlugin"&gt;
 *     &lt;property name="enableJsonFormat" value="true"/&gt;
 *     &lt;property name="enableDateTimeFormat" value="true"/&gt;
 *     &lt;property name="generateGetters" value="false"/&gt;
 *     &lt;property name="generateSetters" value="false"/&gt;
 *     &lt;property name="dateTimePattern" value="yyyy-MM-dd HH:mm:ss"/&gt;
 *     &lt;property name="timezone" value="GMT+8"/&gt;
 * &lt;/plugin&gt;
 * </pre>
 * 
 * @author Generated by MyBatis Generator
 * @version 1.0
 * @since 1.0
 */
public class DomainModelPlugin extends PluginAdapter {

    // Configuration property keys
    private static final String ENABLE_JSON_FORMAT = "enableJsonFormat";
    private static final String ENABLE_DATE_TIME_FORMAT = "enableDateTimeFormat";
    private static final String GENERATE_GETTERS = "generateGetters";
    private static final String GENERATE_SETTERS = "generateSetters";
    private static final String DATE_TIME_PATTERN = "dateTimePattern";
    private static final String TIMEZONE = "timezone";
    
    // Default values
    private static final String DEFAULT_DATE_TIME_PATTERN = "yyyy-MM-dd HH:mm:ss";
    private static final String DEFAULT_TIMEZONE = "GMT+8";
    
    // Annotation class names
    private static final String JSON_FORMAT_CLASS = "com.fasterxml.jackson.annotation.JsonFormat";
    private static final String DATE_TIME_FORMAT_CLASS = "org.springframework.format.annotation.DateTimeFormat";
    
    // Configuration fields
    private boolean enableJsonFormat = true;
    private boolean enableDateTimeFormat = true;
    private boolean generateGetters = true;
    private boolean generateSetters = true;
    private String dateTimePattern = DEFAULT_DATE_TIME_PATTERN;
    private String timezone = DEFAULT_TIMEZONE;

    @Override
    public boolean validate(List<String> warnings) {
        // Parse configuration properties
        parseConfigurationProperties();
        
        // Validate configuration
        if (dateTimePattern == null || dateTimePattern.trim().isEmpty()) {
            warnings.add("DomainModelPlugin: dateTimePattern is empty, using default: " + DEFAULT_DATE_TIME_PATTERN);
            dateTimePattern = DEFAULT_DATE_TIME_PATTERN;
        }
        
        if (timezone == null || timezone.trim().isEmpty()) {
            warnings.add("DomainModelPlugin: timezone is empty, using default: " + DEFAULT_TIMEZONE);
            timezone = DEFAULT_TIMEZONE;
        }
        
        return true;
    }
    
    /**
     * Parses configuration properties from the plugin configuration.
     */
    private void parseConfigurationProperties() {
        if (properties != null) {
            enableJsonFormat = Boolean.parseBoolean(properties.getProperty(ENABLE_JSON_FORMAT, "true"));
            enableDateTimeFormat = Boolean.parseBoolean(properties.getProperty(ENABLE_DATE_TIME_FORMAT, "true"));
            generateGetters = Boolean.parseBoolean(properties.getProperty(GENERATE_GETTERS, "true"));
            generateSetters = Boolean.parseBoolean(properties.getProperty(GENERATE_SETTERS, "true"));
            dateTimePattern = properties.getProperty(DATE_TIME_PATTERN, DEFAULT_DATE_TIME_PATTERN);
            timezone = properties.getProperty(TIMEZONE, DEFAULT_TIMEZONE);
        }
    }

    @Override
    public boolean modelFieldGenerated(Field field, TopLevelClass topLevelClass, 
                                     IntrospectedColumn introspectedColumn, 
                                     IntrospectedTable introspectedTable, 
                                     ModelClassType modelClassType) {
        
        if (isDateTimeType(introspectedColumn)) {
            try {
                addDateTimeAnnotations(field, topLevelClass);
            } catch (Exception e) {
                System.err.println("Warning: Failed to add date/time annotations to field " 
                    + field.getName() + ": " + e.getMessage());
            }
        }
        
        return super.modelFieldGenerated(field, topLevelClass, introspectedColumn, introspectedTable, modelClassType);
    }

    @Override
    public boolean modelGetterMethodGenerated(Method method, TopLevelClass topLevelClass, 
                                            IntrospectedColumn introspectedColumn, 
                                            IntrospectedTable introspectedTable, 
                                            ModelClassType modelClassType) {
        // Return false to disable getter generation if configured
        return generateGetters;
    }

    @Override
    public boolean modelSetterMethodGenerated(Method method, TopLevelClass topLevelClass, 
                                            IntrospectedColumn introspectedColumn, 
                                            IntrospectedTable introspectedTable, 
                                            ModelClassType modelClassType) {
        // Return false to disable setter generation if configured
        return generateSetters;
    }
    
    /**
     * Adds date/time annotations to the specified field based on configuration.
     * 
     * @param field the field to add annotations to
     * @param topLevelClass the class containing the field
     */
    private void addDateTimeAnnotations(Field field, TopLevelClass topLevelClass) {
        if (enableJsonFormat) {
            addJsonFormatAnnotation(field, topLevelClass);
        }
        
        if (enableDateTimeFormat) {
            addDateTimeFormatAnnotation(field, topLevelClass);
        }
    }
    
    /**
     * Adds @JsonFormat annotation for JSON serialization.
     * 
     * @param field the field to add the annotation to
     * @param topLevelClass the class containing the field
     */
    private void addJsonFormatAnnotation(Field field, TopLevelClass topLevelClass) {
        String annotation = String.format("@JsonFormat(pattern = \"%s\", timezone = \"%s\")", 
                                         dateTimePattern, timezone);
        field.addAnnotation(annotation);
        topLevelClass.addImportedType(new FullyQualifiedJavaType(JSON_FORMAT_CLASS));
    }
    
    /**
     * Adds @DateTimeFormat annotation for Spring MVC binding.
     * 
     * @param field the field to add the annotation to
     * @param topLevelClass the class containing the field
     */
    private void addDateTimeFormatAnnotation(Field field, TopLevelClass topLevelClass) {
        String annotation = String.format("@DateTimeFormat(pattern = \"%s\")", dateTimePattern);
        field.addAnnotation(annotation);
        topLevelClass.addImportedType(new FullyQualifiedJavaType(DATE_TIME_FORMAT_CLASS));
    }
    
    /**
     * Determines if the given column represents a date/time type.
     * 
     * @param column the database column to check
     * @return true if the column is a date/time type, false otherwise
     */
    private boolean isDateTimeType(IntrospectedColumn column) {
        String typeName = column.getJdbcTypeName();
        return "DATE".equalsIgnoreCase(typeName) 
            || "TIME".equalsIgnoreCase(typeName) 
            || "TIMESTAMP".equalsIgnoreCase(typeName);
    }
}