package cloud.catfish.mbg.plugin;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.TopLevelClass;

import java.util.List;

/**
 * MyBatis Generator plugin that automatically adds Lombok annotations to generated model classes.
 * 
 * <p>This plugin enhances the generated model classes by adding commonly used Lombok annotations
 * such as @Getter, @Setter, @ToString, @EqualsAndHashCode, @AllArgsConstructor, @NoArgsConstructor,
 * and @Builder. These annotations help reduce boilerplate code and improve code maintainability.</p>
 * 
 * <p><strong>Features:</strong></p>
 * <ul>
 *   <li>Automatically adds essential Lombok annotations to model classes</li>
 *   <li>Reduces boilerplate code by eliminating the need for manual getter/setter methods</li>
 *   <li>Provides builder pattern support through @Builder annotation</li>
 *   <li>Includes proper toString(), equals(), and hashCode() implementations</li>
 *   <li>Supports both parameterized and no-argument constructors</li>
 * </ul>
 * 
 * <p><strong>Usage:</strong></p>
 * <p>Add this plugin to your MyBatis Generator configuration file:</p>
 * <pre>
 * &lt;plugin type="cloud.catfish.mbg.plugin.LombokAnnotationPlugin"&gt;
 * &lt;/plugin&gt;
 * </pre>
 * 
 * @author Generated by MyBatis Generator
 * @version 1.0
 * @since 1.0
 */
public class LombokAnnotationPlugin extends PluginAdapter {

    private static final String LOMBOK_DATA = "lombok.Data";

    @Override
    public boolean validate(List<String> warnings) {
        return true;
    }

    /**
     * 当基础记录类被生成时调用此方法。
     */
    @Override
    public boolean modelBaseRecordClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        addLombokAnnotations(topLevelClass);
        return true;
    }

    /**
     * Adds configured Lombok annotations to the generated top-level class.
     * 
     * @param topLevelClass the generated model class to enhance with Lombok annotations
     */
    private void addLombokAnnotations(TopLevelClass topLevelClass) {
        try {
            addLombokAnnotation(topLevelClass, LOMBOK_DATA, "@Data");
        } catch (Exception e) {
            // Log error but don't fail the generation process
            System.err.println("Warning: Failed to add Lombok annotations to class " 
                + topLevelClass.getType().getShortName() + ": " + e.getMessage());
        }
    }
    
    /**
     * Adds a single Lombok annotation to the top-level class.
     * 
     * @param topLevelClass the class to add the annotation to
     * @param fullyQualifiedName the fully qualified name of the Lombok annotation
     * @param annotationName the annotation name to add (e.g., "@Getter")
     */
    private void addLombokAnnotation(TopLevelClass topLevelClass, String fullyQualifiedName, String annotationName) {
        topLevelClass.addImportedType(new FullyQualifiedJavaType(fullyQualifiedName));
        topLevelClass.addAnnotation(annotationName);
    }
}