jdbc.driverClass=com.mysql.cj.jdbc.Driver
jdbc.connectionURL=jdbc:mysql://10.0.0.6:13306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
jdbc.userId=root
jdbc.password=mysql123

dto.sql=select * from student
dto.package.name=cloud.catfish.mbg.dto
dto.name=StudentDTO
dto.target.path=C:/Users/feemu/Documents/GitHub/spring-quick-start-generator/mbg/src/main/java/cloud/catfish/mbg/dto